name: "Terraform Deploy Infra"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform -chdir=environments/test init

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=environments/test plan -no-color
        env:
          TF_VAR_my_ip_address: ${{ vars.TF_VAR_my_ip_address }}
          TF_VAR_ssh_key_name: ${{ secrets.TF_VAR_ssh_key_name }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=environments/test apply -auto-approve
        env:
          TF_VAR_my_ip_address: ${{ vars.TF_VAR_my_ip_address }}
          TF_VAR_ssh_key_name: ${{ secrets.TF_VAR_ssh_key_name }}