name: "Terraform Dynamic Deploy"

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Alege mediul pentru deployment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - staging
          - prod

jobs:
  terraform:
    name: "Deploy to ${{ github.event.inputs.target_env }}"
    runs-on: ubuntu-latest
    
    # AICI se întâmplă magia: GitHub caută Environment-ul care se potrivește cu alegerea ta
    environment: ${{ github.event.inputs.target_env || 'test' }}
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-central-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        # Folosim variabila de input pentru a intra în folderul corect
        run: terraform -chdir=environments/${{ github.event.inputs.target_env || 'test' }} init

      - name: Terraform Plan
        run: terraform -chdir=environments/${{ github.event.inputs.target_env || 'test' }} plan -no-color
        env:
          TF_VAR_ssh_key_name: ${{ secrets.TF_VAR_SSH_KEY_NAME }}
          TF_VAR_my_ip_address: ${{ vars.TF_VAR_MY_IP_ADDRESS }}